AREA_OF_LAW = ["Civil Procedure",
"Conflict of Laws",
"Admiralty and Shipping",
"Criminal Law",
"Criminal Procedure and Sentencing",
"Contempt of Court",
"Arbitration",
"Insolvency Law",
"Injunctions",
"Bailment",
"Carriage of Goods by Air and Land",
"Credit and Security",
"Companies",
"Courts and Jurisdiction",
"Revenue Law",
"Words and Phrases",
"Insurance",
"Contract",
"Evidence",
"Debt and Recovery",
"Res Judicata",
"Trusts",
"Damages",
"Designs",
"Banking",
"Probate and Administration",
"Equity",
"Administrative Law",
"Employment Law",
"Tort",
"Land",
"Family Law",
"Choses in Action",
"Building and Construction Law", 
"Mental Disorders and Treatment",
"Intellectual Property",
"Constitutional Law",
"Immigration",
"Legal Profession",
"Gifts",
"Restitution",
"Statutory Interpretation",
"Agency",
"Succession and Wills",
"Limitation of Actions",
"Charities",
"Professions",
"Road Traffic",
"Bills of Exchange and Other Negotiable Instruments",
"Commercial Transactions",
"Confidence"]
# "Trade Marks and Trade Names", is supposed to be under IP, but in pre-2017 cases they are not 